### ISSUE TITLE
Bug in description of this task.

### ISSUE THREAD

**Issue by yevheniiMoroziuk7** [bootcamp-places/online-editor-tasks#4]
Опис таски каже нам "Необхідно реалізувати функцію, яка на вхід прийме стрічку з даними, a має повернути нову стрічку з **мінімальним** та **максимальним** значенням температури."

Приклад каже нам:
 highestAndLowest(data); // '**-4 6**'
 
 Отже з опису хочеться ставити мінімальне значення першим, а максимальне другим.
 
 Тести вимагають зворотнє.

**Comment by dosandk** [comment]
@yevheniiMoroziuk7 fixed
